import React from 'react';
import { Text, StyleSheet } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../navigation/types';
import { colors, fonts } from '../theme/theme';
import { Screen } from '../components/Screen';
import { HeaderBar } from '../components/HeaderBar';

type Props = NativeStackScreenProps<RootStackParamList, 'Legal'>;

// [Placeholder] — swap in your real legal entity name, jurisdiction, and a
// monitored contact address before this is submitted to either store.
const COMPANY = 'UlamHub';
const CONTACT_EMAIL = '[support@yourdomain.com]';
const LAST_UPDATED = '[Month Year]';

interface Section {
  heading: string;
  body: string;
}

const PRIVACY: Section[] = [
  {
    heading: 'What this covers',
    body: `This policy explains what ${COMPANY} collects when you use the app, why, and how you can delete it. It applies to the mobile app and the account you create in it.`,
  },
  {
    heading: 'Account information',
    body: 'When you create an account, we (via Supabase, our authentication and database provider) store your email address and an encrypted password, plus any display name, handle, or avatar you set.',
  },
  {
    heading: 'Content you create',
    body: 'Recipes you add or import, your meal plan, your grocery list, and any kitchen you create or join are stored on your device. If you\'re signed in, this same content is also synced to our cloud database so it\'s available across your devices. Photos you attach to a recipe are currently stored only on your device and are not uploaded to our servers.',
  },
  {
    heading: 'Kitchen crew sharing',
    body: 'If you join a kitchen, the other members can see your display name and browse your recipes. If you request to copy a crew member\'s recipe into your own cookbook, they see your name and the recipe you asked for so they can approve or decline it.',
  },
  {
    heading: 'AI features',
    body: `Kitchen AI, Leftover Alchemist, Ingredient Scanner, Party Planner, Recipe Story, and Support Chat send the text or photo you submit to OpenAI to generate a response. We require a signed-in session for these features so we can prevent abuse of this — we do not use your content to train our own models.`,
  },
  {
    heading: 'What we don\'t do',
    body: 'We don\'t sell your personal information. We don\'t share your content with anyone outside the service providers above (Supabase for hosting, OpenAI for AI features) needed to run the app.',
  },
  {
    heading: 'Deleting your data',
    body: 'You can permanently delete your account and everything tied to it — recipes, meal plan, grocery list, and kitchen membership — at any time from Profile → Account → Delete account. This can\'t be undone.',
  },
  {
    heading: 'Children',
    body: `${COMPANY} is not directed at children under 13, and we don't knowingly collect information from them.`,
  },
  {
    heading: 'Changes to this policy',
    body: 'If this policy changes in a material way, we\'ll update the date below and let you know in the app.',
  },
  {
    heading: 'Contact',
    body: `Questions about this policy or your data — including requests to delete or export it — can be sent to ${CONTACT_EMAIL}.`,
  },
];

const TERMS: Section[] = [
  {
    heading: 'Agreement',
    body: `These terms govern your use of ${COMPANY}. By creating an account or using the app, you agree to them.`,
  },
  {
    heading: 'Your account',
    body: 'You\'re responsible for the accuracy of the information you provide and for anything that happens under your account. Let us know right away if you believe your account has been compromised.',
  },
  {
    heading: 'Your content',
    body: 'You keep ownership of the recipes, photos, and other content you add. By sharing a recipe — publicly via a link, or with your kitchen crew — you\'re granting the people who can see it permission to view it, and (for kitchen requests you approve) to copy it into their own cookbook.',
  },
  {
    heading: 'Subscriptions',
    body: 'UlamHub Premium is billed through your Apple or Google account on a recurring basis (monthly or annual) until you cancel. It renews automatically at the end of each period unless cancelled at least 24 hours before renewal, in your device\'s subscription settings. Any free trial converts to a paid subscription unless cancelled before it ends.',
  },
  {
    heading: 'AI-generated content — please read',
    body: 'Recipes, substitutions, and suggestions generated by our AI features are a starting point, not verified professional advice. AI can make mistakes, including about ingredient substitutions, quantities, and allergens. Always use your own judgment — especially around food safety, allergies, and dietary restrictions — before cooking or serving anything based on AI-generated content.',
  },
  {
    heading: 'Acceptable use',
    body: 'Don\'t use the app to scrape, abuse, or overload our AI features or backend, impersonate someone else, or upload content you don\'t have the right to share.',
  },
  {
    heading: 'Termination',
    body: 'You can delete your account at any time from Profile → Account. We may suspend or terminate access for accounts that violate these terms.',
  },
  {
    heading: 'Disclaimer',
    body: `${COMPANY} is provided "as is," without warranties of any kind. We don't guarantee the app, or anything it generates, will be uninterrupted, error-free, or fit for a particular purpose.`,
  },
  {
    heading: 'Limitation of liability',
    body: `To the extent permitted by law, ${COMPANY} isn't liable for indirect, incidental, or consequential damages arising from your use of the app, including from following an AI-generated recipe or suggestion.`,
  },
  {
    heading: 'Changes to these terms',
    body: 'If these terms change in a material way, we\'ll update the date below and let you know in the app.',
  },
  {
    heading: 'Contact',
    body: `Questions about these terms can be sent to ${CONTACT_EMAIL}.`,
  },
];

export function LegalScreen({ route, navigation }: Props) {
  const { doc } = route.params;
  const sections = doc === 'privacy' ? PRIVACY : TERMS;

  return (
    <Screen>
      <HeaderBar title={doc === 'privacy' ? 'Privacy Policy' : 'Terms of Service'} onBack={() => navigation.goBack()} />
      <Text style={styles.updated}>Last updated {LAST_UPDATED}</Text>
      {sections.map((s) => (
        <React.Fragment key={s.heading}>
          <Text style={styles.heading}>{s.heading}</Text>
          <Text style={styles.body}>{s.body}</Text>
        </React.Fragment>
      ))}
    </Screen>
  );
}

const styles = StyleSheet.create({
  updated: { fontSize: 12.5, color: colors.tertiaryText, marginTop: 14, fontFamily: fonts.bodySemiBold },
  heading: { fontFamily: fonts.heading, fontSize: 17, color: colors.ink, marginTop: 22 },
  body: { fontSize: 14, color: colors.sageMuted, lineHeight: 21, marginTop: 8 },
});
