import {
  Recipe,
  PlanDay,
  GroceryGroup,
  Country,
  Region,
  Diet,
  Household,
  Skill,
} from '../types/models';

// Ported from design/UlamHub.dc.html — REGIONS/DIETS/HOUSEHOLDS/SKILLS/ULAM constants
// and the `recipes` + `adobo` sample data in the prototype's Component class.
// Filipino dishes are the original seed set; other countries were added later
// so the app isn't limited to one cuisine.

export const COUNTRIES: Country[] = [
  'Filipino',
  'Italian',
  'American',
  'Mexican',
  'Japanese',
  'Indian',
  'Chinese',
  'Greek',
  'Thai',
  'Korean',
  'Vietnamese',
  'French',
  'Spanish',
  'Lebanese',
];

// Philippine regional styles — only meaningful as a secondary tag on Filipino dishes.
export const REGIONS: Region[] = [
  'Ilocano',
  'Kapampangan',
  'Bicolano',
  'Batangueño',
  'Visayan',
  'Chavacano',
  'Maguindanaoan',
];

export const DIETS: Diet[] = ['Vegetarian', 'Halal', 'Low-sodium', 'Diabetic-friendly'];

export const HOUSEHOLDS: [Household, string][] = [
  ['solo', 'Just me'],
  ['couple', 'Couple'],
  ['family', 'Family'],
  ['multigen', 'Multi-gen home'],
];

export const SKILLS: [Skill, string][] = [
  ['beginner', 'Beginner'],
  ['home', 'Home cook'],
  ['pro', 'Experienced'],
];

export const ULAM = ['All', 'Adobo', 'Sinigang', 'Kare-Kare', 'Ginataan', 'Inihaw', 'Kilawin', 'Guisado'];

const adoboIngredients = [
  { name: 'Chicken thighs, bone-in', qty: 1, unit: 'kg', have: false },
  { name: 'Soy sauce', qty: 120, unit: 'ml', have: true },
  { name: 'Cane vinegar', qty: 90, unit: 'ml', have: true },
  { name: 'Garlic, crushed', qty: 8, unit: 'cloves', have: true },
  { name: 'Bay leaves (laurel)', qty: 3, unit: 'pcs', have: true },
  { name: 'Black peppercorns', qty: 1, unit: 'tsp', have: true },
  { name: 'Brown sugar', qty: 1, unit: 'tbsp', have: true },
  { name: 'Water', qty: 240, unit: 'ml', have: true },
  { name: 'Cooking oil', qty: 2, unit: 'tbsp', have: true },
];

const adoboSteps = [
  { n: 1, text: 'Marinate the chicken in soy sauce, half the garlic, and the peppercorns. Rest 30 minutes.', sec: 1800, tl: '30 min' },
  { n: 2, text: 'Sear the chicken in hot oil, skin-side down, until deeply browned — about 6 minutes.', sec: 360, tl: '6 min' },
  { n: 3, text: 'Add the remaining garlic, bay leaves, and water. Bring to a gentle boil.', sec: 0 },
  { n: 4, text: 'Pour in the vinegar. Do not stir — let it simmer 5 minutes to cook off the sharp edge.', sec: 300, tl: '5 min' },
  { n: 5, text: 'Lower the heat, cover, and simmer 20 minutes until the chicken is fork-tender.', sec: 1200, tl: '20 min' },
  { n: 6, text: 'Stir in the sugar. Simmer uncovered 8 minutes to reduce the sauce until glossy.', sec: 480, tl: '8 min' },
  { n: 7, text: 'Taste and adjust. Serve hot over freshly steamed rice.', sec: 0 },
];

const adoboSaucePairings = [
  { name: 'Sukang sawsawan', note: 'Cane vinegar, garlic, siling labuyo' },
  { name: 'Toyomansi', note: 'Soy sauce + fresh calamansi' },
  { name: 'Spiced vinegar', note: 'With red onion & cracked pepper' },
];

const adoboFlavorBalance = [
  { label: 'Sour', val: 55, color: '#8BAF3E' },
  { label: 'Salty', val: 72, color: '#E0982F' },
  { label: 'Sweet', val: 26, color: '#D98A8A' },
];

const genericFlavorBalance = [
  { label: 'Sour', val: 40, color: '#8BAF3E' },
  { label: 'Salty', val: 55, color: '#E0982F' },
  { label: 'Sweet', val: 35, color: '#D98A8A' },
];

const genericSaucePairings = [
  { name: 'Toyomansi', note: 'Soy sauce + fresh calamansi' },
  { name: 'Spiced vinegar', note: 'With red onion & cracked pepper' },
];

function genericSteps(name: string): Recipe['steps'] {
  return [
    { n: 1, text: `Prep all ingredients for ${name} — wash, slice, and measure everything before you start cooking.`, sec: 0 },
    { n: 2, text: 'Sauté the aromatics (garlic, onion, tomato) in oil until fragrant.', sec: 240, tl: '4 min' },
    { n: 3, text: 'Add the main ingredient and cook through, stirring occasionally.', sec: 600, tl: '10 min' },
    { n: 4, text: 'Simmer until the flavors come together and everything is tender.', sec: 900, tl: '15 min' },
    { n: 5, text: 'Taste, adjust seasoning, and serve hot with rice.', sec: 0 },
  ];
}

function genericIngredients(): Recipe['ingredients'] {
  return [
    { name: 'Main protein or vegetable', qty: 500, unit: 'g', have: false },
    { name: 'Garlic, minced', qty: 4, unit: 'cloves', have: true },
    { name: 'Onion, sliced', qty: 1, unit: 'pc', have: true },
    { name: 'Cooking oil', qty: 2, unit: 'tbsp', have: true },
    { name: 'Salt & pepper', qty: 1, unit: 'tsp', have: true },
  ];
}

export const RECIPE_SEED: Recipe[] = [
  {
    id: 'adobo',
    name: 'Chicken Adobo',
    photoAsset: require('../../assets/dishes/adobo.jpg'),
    country: 'Filipino',
    region: 'Tagalog',
    type: 'Guisado',
    time: 45,
    kcal: 420,
    rating: 4.8,
    cooks: 1240,
    budget: '$',
    diff: 'Home cook',
    author: 'Lola Nena',
    servingsBase: 4,
    ingredients: adoboIngredients,
    steps: adoboSteps,
    nutrition: { protein: 34, carbs: 9, fat: 27, sodium: 980, fiber: 1 },
    saucePairings: adoboSaucePairings,
    flavorBalance: adoboFlavorBalance,
    dietTags: [],
  },
  {
    id: 'sinigang',
    name: 'Sinigang na Baboy',
    photoAsset: require('../../assets/dishes/sinigang.jpg'),
    country: 'Filipino',
    region: 'Tagalog',
    type: 'Nilaga',
    time: 60,
    kcal: 380,
    rating: 4.7,
    cooks: 980,
    budget: '$$',
    diff: 'Home cook',
    author: 'Maritess R.',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Sinigang na Baboy'),
    nutrition: { protein: 28, carbs: 14, fat: 18, sodium: 760, fiber: 3 },
    saucePairings: genericSaucePairings,
    flavorBalance: [
      { label: 'Sour', val: 78, color: '#8BAF3E' },
      { label: 'Salty', val: 45, color: '#E0982F' },
      { label: 'Sweet', val: 10, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'inasal',
    name: 'Chicken Inasal',
    photoAsset: require('../../assets/dishes/inasal.jpg'),
    country: 'Filipino',
    region: 'Visayan',
    type: 'Inihaw',
    time: 50,
    kcal: 390,
    rating: 4.9,
    cooks: 1520,
    budget: '$$',
    diff: 'Home cook',
    author: 'Bacolod Kusina',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Chicken Inasal'),
    nutrition: { protein: 36, carbs: 4, fat: 22, sodium: 640, fiber: 0 },
    saucePairings: genericSaucePairings,
    flavorBalance: genericFlavorBalance,
    dietTags: [],
  },
  {
    id: 'bicol',
    name: 'Bicol Express',
    photoAsset: require('../../assets/dishes/bicol.jpg'),
    country: 'Filipino',
    region: 'Bicolano',
    type: 'Ginataan',
    time: 40,
    kcal: 460,
    rating: 4.7,
    cooks: 720,
    budget: '$$',
    diff: 'Home cook',
    author: 'Tita Baby',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Bicol Express'),
    nutrition: { protein: 24, carbs: 8, fat: 38, sodium: 820, fiber: 2 },
    saucePairings: genericSaucePairings,
    flavorBalance: [
      { label: 'Sour', val: 15, color: '#8BAF3E' },
      { label: 'Salty', val: 60, color: '#E0982F' },
      { label: 'Sweet', val: 20, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'karekare',
    name: 'Kare-Kare',
    photoAsset: require('../../assets/dishes/karekare.jpg'),
    country: 'Filipino',
    region: 'Kapampangan',
    type: 'Guisado',
    time: 120,
    kcal: 540,
    rating: 4.6,
    cooks: 640,
    budget: '$$$',
    diff: 'Experienced',
    author: 'Chef Aldo',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Kare-Kare'),
    nutrition: { protein: 30, carbs: 20, fat: 34, sodium: 700, fiber: 5 },
    saucePairings: [{ name: 'Bagoong alamang', note: 'Shrimp paste, toasted' }],
    flavorBalance: genericFlavorBalance,
    dietTags: [],
  },
  {
    id: 'pinakbet',
    name: 'Ilocano Pinakbet',
    photoAsset: require('../../assets/dishes/pinakbet.jpg'),
    country: 'Filipino',
    region: 'Ilocano',
    type: 'Guisado',
    time: 35,
    kcal: 210,
    rating: 4.5,
    cooks: 540,
    budget: '$',
    diff: 'Beginner',
    author: 'Manang Rosa',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Ilocano Pinakbet'),
    nutrition: { protein: 10, carbs: 22, fat: 8, sodium: 540, fiber: 7 },
    saucePairings: [{ name: 'Bagoong isda', note: 'Fermented fish sauce' }],
    flavorBalance: genericFlavorBalance,
    dietTags: ['Vegetarian'],
  },
  {
    id: 'laing',
    name: 'Laing',
    photoAsset: require('../../assets/dishes/laing.jpg'),
    country: 'Filipino',
    region: 'Bicolano',
    type: 'Ginataan',
    time: 55,
    kcal: 280,
    rating: 4.6,
    cooks: 610,
    budget: '$',
    diff: 'Home cook',
    author: 'Tita Baby',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Laing'),
    nutrition: { protein: 8, carbs: 12, fat: 24, sodium: 480, fiber: 6 },
    saucePairings: genericSaucePairings,
    flavorBalance: [
      { label: 'Sour', val: 10, color: '#8BAF3E' },
      { label: 'Salty', val: 50, color: '#E0982F' },
      { label: 'Sweet', val: 15, color: '#D98A8A' },
    ],
    dietTags: ['Vegetarian'],
  },
  {
    id: 'kilawin',
    name: 'Kilawin Tanigue',
    photoAsset: require('../../assets/dishes/kilawin.jpg'),
    country: 'Filipino',
    region: 'Visayan',
    type: 'Kilawin',
    time: 25,
    kcal: 190,
    rating: 4.4,
    cooks: 330,
    budget: '$$',
    diff: 'Home cook',
    author: 'Cebu Eats',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Kilawin Tanigue'),
    nutrition: { protein: 26, carbs: 4, fat: 6, sodium: 420, fiber: 1 },
    saucePairings: [{ name: 'Suka\'t sili', note: 'Vinegar with chopped chili' }],
    flavorBalance: [
      { label: 'Sour', val: 70, color: '#8BAF3E' },
      { label: 'Salty', val: 35, color: '#E0982F' },
      { label: 'Sweet', val: 5, color: '#D98A8A' },
    ],
    dietTags: ['Low-sodium'],
  },
  {
    id: 'carbonara',
    name: 'Spaghetti Carbonara',
    country: 'Italian',
    type: 'Pasta',
    time: 30,
    kcal: 520,
    rating: 4.8,
    cooks: 890,
    budget: '$$',
    diff: 'Home cook',
    author: 'Nonna Lucia',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Spaghetti Carbonara'),
    nutrition: { protein: 22, carbs: 58, fat: 20, sodium: 640, fiber: 2 },
    saucePairings: [{ name: 'Extra parmesan', note: 'Finely grated, for the table' }],
    flavorBalance: [
      { label: 'Sour', val: 10, color: '#8BAF3E' },
      { label: 'Salty', val: 65, color: '#E0982F' },
      { label: 'Sweet', val: 5, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'margherita',
    name: 'Margherita Pizza',
    country: 'Italian',
    type: 'Baked',
    time: 40,
    kcal: 480,
    rating: 4.7,
    cooks: 760,
    budget: '$',
    diff: 'Home cook',
    author: 'Pizzeria Bella',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Margherita Pizza'),
    nutrition: { protein: 18, carbs: 62, fat: 16, sodium: 720, fiber: 3 },
    saucePairings: [{ name: 'Chili oil', note: 'Drizzle at the table' }],
    flavorBalance: [
      { label: 'Sour', val: 25, color: '#8BAF3E' },
      { label: 'Salty', val: 55, color: '#E0982F' },
      { label: 'Sweet', val: 30, color: '#D98A8A' },
    ],
    dietTags: ['Vegetarian'],
  },
  {
    id: 'pulledpork',
    name: 'BBQ Pulled Pork',
    country: 'American',
    type: 'Smoked',
    time: 240,
    kcal: 560,
    rating: 4.7,
    cooks: 610,
    budget: '$$',
    diff: 'Experienced',
    author: 'Smokehouse Sam',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('BBQ Pulled Pork'),
    nutrition: { protein: 38, carbs: 24, fat: 30, sodium: 890, fiber: 1 },
    saucePairings: [{ name: 'Vinegar-based BBQ sauce', note: 'Tangy, Carolina-style' }],
    flavorBalance: [
      { label: 'Sour', val: 30, color: '#8BAF3E' },
      { label: 'Salty', val: 50, color: '#E0982F' },
      { label: 'Sweet', val: 55, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'cheeseburger',
    name: 'Classic Cheeseburger',
    country: 'American',
    type: 'Grilled',
    time: 25,
    kcal: 600,
    rating: 4.6,
    cooks: 1040,
    budget: '$',
    diff: 'Beginner',
    author: 'Diner Classics',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Classic Cheeseburger'),
    nutrition: { protein: 30, carbs: 34, fat: 36, sodium: 820, fiber: 2 },
    saucePairings: [{ name: 'Burger sauce', note: 'Ketchup, mustard, mayo blend' }],
    flavorBalance: [
      { label: 'Sour', val: 15, color: '#8BAF3E' },
      { label: 'Salty', val: 60, color: '#E0982F' },
      { label: 'Sweet', val: 20, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'tacos',
    name: 'Chicken Tacos',
    country: 'Mexican',
    type: 'Grilled',
    time: 30,
    kcal: 410,
    rating: 4.7,
    cooks: 880,
    budget: '$',
    diff: 'Beginner',
    author: 'Taqueria Rosita',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Chicken Tacos'),
    nutrition: { protein: 28, carbs: 30, fat: 16, sodium: 610, fiber: 4 },
    saucePairings: [{ name: 'Salsa verde', note: 'Tomatillo, lime, cilantro' }],
    flavorBalance: [
      { label: 'Sour', val: 55, color: '#8BAF3E' },
      { label: 'Salty', val: 45, color: '#E0982F' },
      { label: 'Sweet', val: 10, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'enchiladas',
    name: 'Beef Enchiladas',
    country: 'Mexican',
    type: 'Baked',
    time: 55,
    kcal: 540,
    rating: 4.6,
    cooks: 470,
    budget: '$$',
    diff: 'Home cook',
    author: 'Cocina Mendez',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Beef Enchiladas'),
    nutrition: { protein: 32, carbs: 40, fat: 28, sodium: 760, fiber: 5 },
    saucePairings: [{ name: 'Red chili sauce', note: 'Simmered with dried chiles' }],
    flavorBalance: [
      { label: 'Sour', val: 20, color: '#8BAF3E' },
      { label: 'Salty', val: 55, color: '#E0982F' },
      { label: 'Sweet', val: 15, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'greencurry',
    name: 'Green Curry Chicken',
    country: 'Thai',
    type: 'Curry',
    time: 40,
    kcal: 480,
    rating: 4.7,
    cooks: 690,
    budget: '$$',
    diff: 'Home cook',
    author: 'Bangkok Kitchen',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Green Curry Chicken'),
    nutrition: { protein: 26, carbs: 14, fat: 34, sodium: 780, fiber: 3 },
    saucePairings: [{ name: 'Fish sauce & lime', note: 'For extra brightness at the table' }],
    flavorBalance: [
      { label: 'Sour', val: 40, color: '#8BAF3E' },
      { label: 'Salty', val: 55, color: '#E0982F' },
      { label: 'Sweet', val: 30, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'bibimbap',
    name: 'Bibimbap',
    country: 'Korean',
    type: 'Rice Bowl',
    time: 35,
    kcal: 520,
    rating: 4.8,
    cooks: 810,
    budget: '$$',
    diff: 'Home cook',
    author: 'Seoul Table',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Bibimbap'),
    nutrition: { protein: 24, carbs: 62, fat: 18, sodium: 680, fiber: 6 },
    saucePairings: [{ name: 'Gochujang', note: 'Sweet-spicy chili paste, stirred in at the table' }],
    flavorBalance: [
      { label: 'Sour', val: 15, color: '#8BAF3E' },
      { label: 'Salty', val: 50, color: '#E0982F' },
      { label: 'Sweet', val: 35, color: '#D98A8A' },
    ],
    dietTags: ['Vegetarian'],
  },
  {
    id: 'pho',
    name: 'Beef Pho',
    country: 'Vietnamese',
    type: 'Soup',
    time: 90,
    kcal: 420,
    rating: 4.9,
    cooks: 1120,
    budget: '$$',
    diff: 'Experienced',
    author: 'Hanoi Street Kitchen',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Beef Pho'),
    nutrition: { protein: 28, carbs: 46, fat: 10, sodium: 890, fiber: 2 },
    saucePairings: [{ name: 'Hoisin & sriracha', note: 'Dipped or stirred in, to taste' }],
    flavorBalance: [
      { label: 'Sour', val: 30, color: '#8BAF3E' },
      { label: 'Salty', val: 60, color: '#E0982F' },
      { label: 'Sweet', val: 20, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'coqauvin',
    name: 'Coq au Vin',
    country: 'French',
    type: 'Braised',
    time: 105,
    kcal: 560,
    rating: 4.7,
    cooks: 340,
    budget: '$$$',
    diff: 'Experienced',
    author: 'Bistro Lumière',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Coq au Vin'),
    nutrition: { protein: 38, carbs: 12, fat: 30, sodium: 620, fiber: 2 },
    saucePairings: [{ name: 'Reduced red wine sauce', note: 'Spooned over at the end' }],
    flavorBalance: [
      { label: 'Sour', val: 25, color: '#8BAF3E' },
      { label: 'Salty', val: 45, color: '#E0982F' },
      { label: 'Sweet', val: 15, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'paella',
    name: 'Seafood Paella',
    country: 'Spanish',
    type: 'Rice',
    time: 60,
    kcal: 510,
    rating: 4.8,
    cooks: 590,
    budget: '$$$',
    diff: 'Experienced',
    author: 'Casa Valencia',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Seafood Paella'),
    nutrition: { protein: 32, carbs: 58, fat: 14, sodium: 740, fiber: 3 },
    saucePairings: [{ name: 'Alioli', note: 'Garlicky, served on the side' }],
    flavorBalance: [
      { label: 'Sour', val: 15, color: '#8BAF3E' },
      { label: 'Salty', val: 55, color: '#E0982F' },
      { label: 'Sweet', val: 10, color: '#D98A8A' },
    ],
    dietTags: [],
  },
  {
    id: 'shawarma',
    name: 'Chicken Shawarma',
    country: 'Lebanese',
    type: 'Grilled',
    time: 45,
    kcal: 460,
    rating: 4.7,
    cooks: 630,
    budget: '$$',
    diff: 'Home cook',
    author: 'Beirut Corner',
    servingsBase: 4,
    ingredients: genericIngredients(),
    steps: genericSteps('Chicken Shawarma'),
    nutrition: { protein: 34, carbs: 20, fat: 22, sodium: 700, fiber: 3 },
    saucePairings: [{ name: 'Garlic toum', note: 'Whipped garlic sauce' }],
    flavorBalance: [
      { label: 'Sour', val: 35, color: '#8BAF3E' },
      { label: 'Salty', val: 50, color: '#E0982F' },
      { label: 'Sweet', val: 10, color: '#D98A8A' },
    ],
    dietTags: [],
  },
];

export function seedPlan(): PlanDay[] {
  const rows: [string, string, string | null, string | null, string | null, string | null][] = [
    ['Mon', '9', 'Champorado', 'adobo', 'Turon', 'sinigang'],
    ['Tue', '10', 'Tapsilog', 'pinakbet', null, 'inasal'],
    ['Wed', '11', 'Pandesal', null, 'Puto', 'karekare'],
    ['Thu', '12', 'Arroz caldo', 'laing', 'Banana cue', null],
    ['Fri', '13', 'Longsilog', 'bicol', null, 'kilawin'],
    ['Sat', '14', 'Goto', 'adobo', 'Halo-halo', null],
    ['Sun', '15', null, 'Lechon kawali', null, 'Nilagang Baka'],
  ];
  return rows.map(([day, date, breakfast, lunch, merienda, dinner]) => ({
    day,
    date,
    breakfast,
    lunch,
    merienda,
    dinner,
  }));
}

export function seedGrocery(): GroceryGroup[] {
  return [
    {
      name: 'Produce',
      sub: '',
      items: [
        { n: 'Garlic', q: '2 bulbs', checked: false },
        { n: 'Kalamansi', q: '12 pcs', checked: false },
        { n: 'Long beans', q: '1 bundle', checked: false },
        { n: 'Eggplant', q: '3 pcs', checked: false },
        { n: 'Water spinach', q: '1 bundle', checked: false },
      ],
    },
    {
      name: 'Meat',
      sub: '',
      items: [
        { n: 'Chicken thighs', q: '1 kg', checked: false },
        { n: 'Pork belly', q: '750 g', checked: false },
      ],
    },
    {
      name: 'Seafood',
      sub: '',
      items: [
        { n: 'Tanigue steak', q: '500 g', checked: false },
        { n: 'Shrimp paste', q: '1 jar', checked: false },
      ],
    },
    {
      name: 'Pantry & Condiments',
      sub: '',
      items: [
        { n: 'Soy sauce', q: '1 btl', checked: false },
        { n: 'Cane vinegar', q: '1 btl', checked: false },
        { n: 'Coconut milk', q: '2 cans', checked: false },
        { n: 'Bay leaves', q: '1 pack', checked: false },
        { n: 'Rice', q: '5 kg', checked: false },
      ],
    },
  ];
}

export const ABROAD_SUBSTITUTIONS: [string, string][] = [
  ['Banana leaves', 'Parchment paper'],
  ['Kalamansi', 'Lime + lemon (equal mix)'],
  ['Bagoong (shrimp paste)', 'Anchovy paste'],
  ['Puto rice flour', 'Regular rice flour + baking powder'],
];
